export type Car = {
  id: string
  make: string
  model: string
  variant: string
  year: number
  color: string
  mileage: number
  transmission: "Automatic" | "Manual"
  fuelType: "Gasoline" | "Diesel"
  condition: "Excellent" | "Good" | "Fair"
  price: number
  location: string
  image: string
  bodyType: "Sedan" | "SUV" | "Hatchback" | "Pickup" | "MPV"
}

// Specs and pricing modeled on real Philippine used-car market data
// (typical Metro Manila listings for these exact variants, 2024-2025).
export const inventory: Car[] = [
  {
    id: "phm-001",
    make: "Toyota",
    model: "Vios",
    variant: "1.3 XE CVT",
    year: 2020,
    color: "Pearl White",
    mileage: 42000,
    transmission: "Automatic",
    fuelType: "Gasoline",
    condition: "Excellent",
    price: 595000,
    location: "Quezon City",
    image: "/cars/toyota-vios-white.jpg",
    bodyType: "Sedan",
  },
  {
    id: "phm-002",
    make: "Honda",
    model: "City",
    variant: "1.5 VX Navi CVT",
    year: 2020,
    color: "Lunar Silver",
    mileage: 38000,
    transmission: "Automatic",
    fuelType: "Gasoline",
    condition: "Excellent",
    price: 695000,
    location: "Pasig City",
    image: "/cars/honda-city-silver.jpg",
    bodyType: "Sedan",
  },
  {
    id: "phm-003",
    make: "Honda",
    model: "Civic",
    variant: "1.5 RS Turbo CVT",
    year: 2021,
    color: "Crystal Black Pearl",
    mileage: 31000,
    transmission: "Automatic",
    fuelType: "Gasoline",
    condition: "Excellent",
    price: 1185000,
    location: "Makati City",
    image: "/cars/honda-civic-black.jpg",
    bodyType: "Sedan",
  },
  {
    id: "phm-004",
    make: "Toyota",
    model: "Innova",
    variant: "2.8 E Diesel AT",
    year: 2019,
    color: "Freedom White",
    mileage: 67000,
    transmission: "Automatic",
    fuelType: "Diesel",
    condition: "Excellent",
    price: 945000,
    location: "Pasig City",
    image: "/cars/toyota-innova-white.jpg",
    bodyType: "MPV",
  },
  {
    id: "phm-005",
    make: "Toyota",
    model: "Fortuner",
    variant: "2.4 G 4x2 Diesel AT",
    year: 2020,
    color: "Attitude Black",
    mileage: 58000,
    transmission: "Automatic",
    fuelType: "Diesel",
    condition: "Excellent",
    price: 1585000,
    location: "Alabang",
    image: "/cars/toyota-fortuner-gray.jpg",
    bodyType: "SUV",
  },
  {
    id: "phm-006",
    make: "Mitsubishi",
    model: "Montero Sport",
    variant: "GLS 2.4 4x2 AT",
    year: 2018,
    color: "Jet Black Mica",
    mileage: 78000,
    transmission: "Automatic",
    fuelType: "Diesel",
    condition: "Good",
    price: 1095000,
    location: "Quezon City",
    image: "/cars/mitsubishi-montero-black.jpg",
    bodyType: "SUV",
  },
  {
    id: "phm-007",
    make: "Ford",
    model: "Ranger",
    variant: "2.0 Wildtrak 4x2 Bi-Turbo AT",
    year: 2020,
    color: "Race Red",
    mileage: 49000,
    transmission: "Automatic",
    fuelType: "Diesel",
    condition: "Excellent",
    price: 1325000,
    location: "Pasig City",
    image: "/cars/ford-ranger-red.jpg",
    bodyType: "Pickup",
  },
  {
    id: "phm-008",
    make: "Nissan",
    model: "Almera",
    variant: "1.5 VL CVT",
    year: 2019,
    color: "Storm Blue",
    mileage: 54000,
    transmission: "Automatic",
    fuelType: "Gasoline",
    condition: "Good",
    price: 485000,
    location: "Quezon City",
    image: "/cars/nissan-almera-blue.jpg",
    bodyType: "Sedan",
  },
  {
    id: "phm-009",
    make: "Hyundai",
    model: "Accent",
    variant: "1.6 CRDi GL Diesel MT",
    year: 2018,
    color: "Sleek Silver",
    mileage: 89000,
    transmission: "Manual",
    fuelType: "Diesel",
    condition: "Good",
    price: 425000,
    location: "Quezon City",
    image: "/cars/hyundai-accent-silver.jpg",
    bodyType: "Sedan",
  },
  {
    id: "phm-010",
    make: "Mazda",
    model: "Mazda 3",
    variant: "2.0 Premium Hatchback Skyactiv-G AT",
    year: 2020,
    color: "Soul Red Crystal",
    mileage: 36000,
    transmission: "Automatic",
    fuelType: "Gasoline",
    condition: "Excellent",
    price: 1095000,
    location: "Makati City",
    image: "/cars/mazda3-red.jpg",
    bodyType: "Hatchback",
  },
  {
    id: "phm-011",
    make: "Suzuki",
    model: "Ertiga",
    variant: "1.5 GL Sport AT",
    year: 2020,
    color: "Silky Silver",
    mileage: 47000,
    transmission: "Automatic",
    fuelType: "Gasoline",
    condition: "Excellent",
    price: 685000,
    location: "Pasig City",
    image: "/cars/suzuki-ertiga-silver.jpg",
    bodyType: "MPV",
  },
  {
    id: "phm-012",
    make: "Toyota",
    model: "Wigo",
    variant: "1.0 G AT",
    year: 2021,
    color: "Cyan Metallic",
    mileage: 28000,
    transmission: "Automatic",
    fuelType: "Gasoline",
    condition: "Excellent",
    price: 485000,
    location: "Quezon City",
    image: "/cars/toyota-wigo-cyan.jpg",
    bodyType: "Hatchback",
  },
  {
    id: "phm-013",
    make: "Mitsubishi",
    model: "Mirage G4",
    variant: "1.2 GLS CVT",
    year: 2020,
    color: "Sand Yellow",
    mileage: 51000,
    transmission: "Automatic",
    fuelType: "Gasoline",
    condition: "Good",
    price: 445000,
    location: "Alabang",
    image: "/cars/mitsubishi-mirage-g4-yellow.jpg",
    bodyType: "Sedan",
  },
  {
    id: "phm-014",
    make: "Ford",
    model: "Everest",
    variant: "2.0 Titanium+ 4x2 AT",
    year: 2019,
    color: "Diffused Silver",
    mileage: 62000,
    transmission: "Automatic",
    fuelType: "Diesel",
    condition: "Excellent",
    price: 1295000,
    location: "Makati City",
    image: "/cars/ford-everest-silver.jpg",
    bodyType: "SUV",
  },
  {
    id: "phm-015",
    make: "Mazda",
    model: "CX-5",
    variant: "2.0 Pro Skyactiv-G AT",
    year: 2019,
    color: "Machine Gray",
    mileage: 53000,
    transmission: "Automatic",
    fuelType: "Gasoline",
    condition: "Excellent",
    price: 1175000,
    location: "Makati City",
    image: "/cars/mazda-cx5-gray.jpg",
    bodyType: "SUV",
  },
  {
    id: "phm-016",
    make: "Toyota",
    model: "Hilux",
    variant: "2.4 G 4x2 Diesel AT",
    year: 2020,
    color: "Super White",
    mileage: 56000,
    transmission: "Automatic",
    fuelType: "Diesel",
    condition: "Excellent",
    price: 1195000,
    location: "Alabang",
    image: "/cars/toyota-hilux-white.jpg",
    bodyType: "Pickup",
  },
  {
    id: "phm-017",
    make: "Mitsubishi",
    model: "Strada",
    variant: "GLS 2.4 4x2 AT",
    year: 2019,
    color: "Pyrenees Black",
    mileage: 72000,
    transmission: "Automatic",
    fuelType: "Diesel",
    condition: "Good",
    price: 995000,
    location: "Quezon City",
    image: "/cars/mitsubishi-strada-black.jpg",
    bodyType: "Pickup",
  },
  {
    id: "phm-018",
    make: "Honda",
    model: "BR-V",
    variant: "1.5 V CVT",
    year: 2020,
    color: "Modern Steel Metallic",
    mileage: 49000,
    transmission: "Automatic",
    fuelType: "Gasoline",
    condition: "Excellent",
    price: 785000,
    location: "Pasig City",
    image: "/cars/honda-brv-gray.jpg",
    bodyType: "MPV",
  },
  {
    id: "phm-019",
    make: "Hyundai",
    model: "Tucson",
    variant: "2.0 GLS CRDi AT",
    year: 2018,
    color: "Phantom Black",
    mileage: 81000,
    transmission: "Automatic",
    fuelType: "Diesel",
    condition: "Good",
    price: 825000,
    location: "Quezon City",
    image: "/cars/hyundai-tucson-black.jpg",
    bodyType: "SUV",
  },
  {
    id: "phm-020",
    make: "Kia",
    model: "Picanto",
    variant: "1.2 EX MT",
    year: 2021,
    color: "Signal Red",
    mileage: 24000,
    transmission: "Manual",
    fuelType: "Gasoline",
    condition: "Excellent",
    price: 445000,
    location: "Alabang",
    image: "/cars/kia-picanto-red.jpg",
    bodyType: "Hatchback",
  },
]

export function formatPHP(value: number) {
  return new Intl.NumberFormat("en-PH", {
    style: "currency",
    currency: "PHP",
    maximumFractionDigits: 0,
  }).format(value)
}

export function formatMileage(km: number) {
  return new Intl.NumberFormat("en-PH").format(km) + " km"
}
